apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{APPNAME}"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "{APPNAME}"
  template:
    metadata:
      labels:
        app: "{APPNAME}"
    spec:
      containers:
        - name: "{APPNAME}"
          image: "{REPO}/{APPNAME}:{TAG}" # Ganti dengan nama image yang sesuai
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: "{APPNAME}"
spec:
  selector:
    app: "{APPNAME}" # Harus cocok dengan label di Deployment
  ports:
    - protocol: TCP
      port: 8000 # Port internal service
      targetPort: 8000 # Port pada container
  type: NodePort # Mengekspos service di luar cluster Minikube
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{APPNAME}"
spec:
  ingressClassName: nginx
  rules:
    - host: django.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{APPNAME}"
                port:
                  number: 8000
